BEGIN;

ALTER TABLE cars ADD COLUMN IF NOT EXISTS model_year integer NOT NULL DEFAULT (EXTRACT(YEAR FROM CURRENT_DATE))::integer;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS color varchar(64) NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_type varchar(16) NOT NULL DEFAULT 'petrol';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS transmission varchar(16) NOT NULL DEFAULT 'manual';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS mileage_km integer NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS num_seats integer NOT NULL DEFAULT 5;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS airbag_count integer NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS airbag_details jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS camera_type varchar(64) NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS air_conditioning boolean NOT NULL DEFAULT false;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS airbags boolean NOT NULL DEFAULT false;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS cruise_control boolean NOT NULL DEFAULT false;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS open_roof boolean NOT NULL DEFAULT false;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS navigation boolean NOT NULL DEFAULT false;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS speakers boolean NOT NULL DEFAULT false;

COMMIT;
