BEGIN;

ALTER TABLE cars DROP COLUMN IF EXISTS model_year;
ALTER TABLE cars DROP COLUMN IF EXISTS color;
ALTER TABLE cars DROP COLUMN IF EXISTS fuel_type;
ALTER TABLE cars DROP COLUMN IF EXISTS transmission;
ALTER TABLE cars DROP COLUMN IF EXISTS mileage_km;
ALTER TABLE cars DROP COLUMN IF EXISTS num_seats;
ALTER TABLE cars DROP COLUMN IF EXISTS airbag_count;
ALTER TABLE cars DROP COLUMN IF EXISTS airbag_details;
ALTER TABLE cars DROP COLUMN IF EXISTS camera_type;
ALTER TABLE cars DROP COLUMN IF EXISTS air_conditioning;
ALTER TABLE cars DROP COLUMN IF EXISTS airbags;
ALTER TABLE cars DROP COLUMN IF EXISTS cruise_control;
ALTER TABLE cars DROP COLUMN IF EXISTS open_roof;
ALTER TABLE cars DROP COLUMN IF EXISTS navigation;
ALTER TABLE cars DROP COLUMN IF EXISTS speakers;

COMMIT;
